feature_list = [
    "Suburb",
    "Address",
    "Rooms",
    "Type",
    "Date",
    "Distance",
    "Postcode",
    "Bathroom",
    "Car",
    "Landsize",
    "BuildingArea",
    "YearBuilt",
    "CouncilArea",
    "Lattitude",
    "Longtitude",
    "Regionname",
    "Propertycount",
    "CrimeRate",
    "NearbySchools",
    "Price",
    "Prediction"
]

feature_form_structure = {
    "General": [
        {
            "Label": "Suburb",
            "Data": {
                "Description": "Please choose a suburb from the list",
                "Form": {
                    "1": "Abbotsford",
                    "2": "Aberfeldie",
                    "3": "Airport West",
                    "4": "Albanvale",
                    "5": "Albert Park",
                    "6": "Albion",
                    "7": "Alphington",
                    "8": "Altona",
                    "9": "Altona Meadows",
                    "10": "Altona North",
                    "11": "Ardeer",
                    "12": "Armadale",
                    "13": "Ascot Vale",
                    "14": "Ashburton",
                    "15": "Ashwood",
                    "16": "Aspendale",
                    "17": "Aspendale Gardens",
                    "18": "Attwood",
                    "19": "Avondale Heights",
                    "20": "Bacchus Marsh",
                    "21": "Balaclava",
                    "22": "Balwyn",
                    "23": "Balwyn North",
                    "24": "Bayswater",
                    "25": "Bayswater North",
                    "26": "Beaconsfield",
                    "27": "Beaconsfield Upper",
                    "28": "Beaumaris",
                    "29": "Bellfield",
                    "30": "Bentleigh",
                    "31": "Bentleigh East",
                    "32": "Berwick",
                    "33": "Black Rock",
                    "34": "Blackburn",
                    "35": "Blackburn North",
                    "36": "Blackburn South",
                    "37": "Bonbeach",
                    "38": "Boronia",
                    "39": "Botanic Ridge",
                    "40": "Box Hill",
                    "41": "Braybrook",
                    "42": "Briar Hill",
                    "43": "Brighton",
                    "44": "Brighton East",
                    "45": "Broadmeadows",
                    "46": "Brookfield",
                    "47": "Brooklyn",
                    "48": "Brunswick",
                    "49": "Brunswick East",
                    "50": "Brunswick West",
                    "51": "Bulleen",
                    "52": "Bullengarook",
                    "53": "Bundoora",
                    "54": "Burnley",
                    "55": "Burnside",
                    "56": "Burnside Heights",
                    "57": "Burwood",
                    "58": "Burwood East",
                    "59": "Cairnlea",
                    "60": "Camberwell",
                    "61": "Campbellfield",
                    "62": "Canterbury",
                    "63": "Carlton",
                    "64": "Carlton North",
                    "65": "Carnegie",
                    "66": "Caroline Springs",
                    "67": "Carrum",
                    "68": "Carrum Downs",
                    "69": "Caulfield",
                    "70": "Caulfield East",
                    "71": "Caulfield North",
                    "72": "Caulfield South",
                    "73": "Chadstone",
                    "74": "Chelsea",
                    "75": "Chelsea Heights",
                    "76": "Cheltenham",
                    "77": "Chirnside Park",
                    "78": "Clarinda",
                    "79": "Clayton",
                    "80": "Clayton South",
                    "81": "Clifton Hill",
                    "82": "Coburg",
                    "83": "Coburg North",
                    "84": "Collingwood",
                    "85": "Coolaroo",
                    "86": "Craigieburn",
                    "87": "Cranbourne",
                    "88": "Cranbourne North",
                    "89": "Cremorne",
                    "90": "Croydon",
                    "91": "Croydon Hills",
                    "92": "Croydon North",
                    "93": "Croydon South",
                    "94": "Dallas",
                    "95": "Dandenong",
                    "96": "Dandenong North",
                    "97": "Deepdene",
                    "98": "Deer Park",
                    "99": "Delahey",
                    "100": "Derrimut",
                    "101": "Diamond Creek",
                    "102": "Diggers Rest",
                    "103": "Dingley Village",
                    "104": "Doncaster",
                    "105": "Doncaster East",
                    "106": "Donvale",
                    "107": "Doreen",
                    "108": "Doveton",
                    "109": "Eaglemont",
                    "110": "East Melbourne",
                    "111": "Edithvale",
                    "112": "Elsternwick",
                    "113": "Eltham",
                    "114": "Eltham North",
                    "115": "Elwood",
                    "116": "Emerald",
                    "117": "Endeavour Hills",
                    "118": "Epping",
                    "119": "Essendon",
                    "120": "Essendon North",
                    "121": "Essendon West",
                    "122": "Fairfield",
                    "123": "Fawkner",
                    "124": "Ferntree Gully",
                    "125": "Fitzroy",
                    "126": "Fitzroy North",
                    "127": "Flemington",
                    "128": "Footscray",
                    "129": "Forest Hill",
                    "130": "Frankston",
                    "131": "Frankston North",
                    "132": "Frankston South",
                    "133": "Gardenvale",
                    "134": "Gisborne",
                    "135": "Gisborne South",
                    "136": "Gladstone Park",
                    "137": "Glen Huntly",
                    "138": "Glen Iris",
                    "139": "Glen Waverley",
                    "140": "Glenroy",
                    "141": "Gowanbrae",
                    "142": "Greensborough",
                    "143": "Greenvale",
                    "144": "Hadfield",
                    "145": "Hallam",
                    "146": "Hampton",
                    "147": "Hampton East",
                    "148": "Hampton Park",
                    "149": "Hawthorn",
                    "150": "Hawthorn East",
                    "151": "Healesville",
                    "152": "Heathmont",
                    "153": "Heidelberg",
                    "154": "Heidelberg Heights",
                    "155": "Heidelberg West",
                    "156": "Highett",
                    "157": "Hillside",
                    "158": "Hoppers Crossing",
                    "159": "Hughesdale",
                    "160": "Huntingdale",
                    "161": "Hurstbridge",
                    "162": "Ivanhoe",
                    "163": "Ivanhoe East",
                    "164": "Jacana",
                    "165": "Kealba",
                    "166": "Keilor",
                    "167": "Keilor Downs",
                    "168": "Keilor East",
                    "169": "Keilor Lodge",
                    "170": "Keilor Park",
                    "171": "Kensington",
                    "172": "Kew",
                    "173": "Kew East",
                    "174": "Keysborough",
                    "175": "Kilsyth",
                    "176": "Kings Park",
                    "177": "Kingsbury",
                    "178": "Kingsville",
                    "179": "Knoxfield",
                    "180": "Kooyong",
                    "181": "Kurunjang",
                    "182": "Lalor",
                    "183": "Langwarrin",
                    "184": "Laverton",
                    "185": "Lower Plenty",
                    "186": "Lysterfield",
                    "187": "Maidstone",
                    "188": "Malvern",
                    "189": "Malvern East",
                    "190": "Maribyrnong",
                    "191": "McKinnon",
                    "192": "Meadow Heights",
                    "193": "Melbourne",
                    "194": "Melton",
                    "195": "Melton South",
                    "196": "Melton West",
                    "197": "Mentone",
                    "198": "Mernda",
                    "199": "Mickleham",
                    "200": "Middle Park",
                    "201": "Mill Park",
                    "202": "Mitcham",
                    "203": "Mont Albert",
                    "204": "Montmorency",
                    "205": "Montrose",
                    "206": "Moonee Ponds",
                    "207": "Moorabbin",
                    "208": "Mooroolbark",
                    "209": "Mordialloc",
                    "210": "Mount Evelyn",
                    "211": "Mount Waverley",
                    "212": "Mulgrave",
                    "213": "Murrumbeena",
                    "214": "Narre Warren",
                    "215": "Newport",
                    "216": "Niddrie",
                    "217": "Noble Park",
                    "218": "North Melbourne",
                    "219": "North Warrandyte",
                    "220": "Northcote",
                    "221": "Notting Hill",
                    "222": "Nunawading",
                    "223": "Oak Park",
                    "224": "Oakleigh",
                    "225": "Oakleigh East",
                    "226": "Oakleigh South",
                    "227": "Officer",
                    "228": "Ormond",
                    "229": "Pakenham",
                    "230": "Parkdale",
                    "231": "Parkville",
                    "232": "Pascoe Vale",
                    "233": "Patterson Lakes",
                    "234": "Plumpton",
                    "235": "Point Cook",
                    "236": "Port Melbourne",
                    "237": "Prahran",
                    "238": "Preston",
                    "239": "Princes Hill",
                    "240": "Research",
                    "241": "Reservoir",
                    "242": "Richmond",
                    "243": "Riddells Creek",
                    "244": "Ringwood",
                    "245": "Ringwood East",
                    "246": "Ringwood North",
                    "247": "Ripponlea",
                    "248": "Rosanna",
                    "249": "Rowville",
                    "250": "Roxburgh Park",
                    "251": "Sandhurst",
                    "252": "Sandringham",
                    "253": "Scoresby",
                    "254": "Seabrook",
                    "255": "Seaford",
                    "256": "Seaholme",
                    "257": "Seddon",
                    "258": "Skye",
                    "259": "South Kingsville",
                    "260": "South Melbourne",
                    "261": "South Morang",
                    "262": "South Yarra",
                    "263": "Southbank",
                    "264": "Spotswood",
                    "265": "Springvale",
                    "266": "Springvale South",
                    "267": "St Albans",
                    "268": "St Helena",
                    "269": "St Kilda",
                    "270": "Strathmore",
                    "271": "Strathmore Heights",
                    "272": "Sunbury",
                    "273": "Sunshine",
                    "274": "Sunshine North",
                    "275": "Sunshine West",
                    "276": "Surrey Hills",
                    "277": "Sydenham",
                    "278": "Tarneit",
                    "279": "Taylors Hill",
                    "280": "Taylors Lakes",
                    "281": "Templestowe",
                    "282": "Templestowe Lower",
                    "283": "The Basin",
                    "284": "Thomastown",
                    "285": "Thornbury",
                    "286": "Toorak",
                    "287": "Travancore",
                    "288": "Truganina",
                    "289": "Tullamarine",
                    "290": "Upwey",
                    "291": "Vermont",
                    "292": "Vermont South",
                    "293": "Viewbank",
                    "294": "Wallan",
                    "295": "Wantirna",
                    "296": "Wantirna South",
                    "297": "Warrandyte",
                    "298": "Waterways",
                    "299": "Watsonia",
                    "300": "Watsonia North",
                    "301": "Wattle Glen",
                    "302": "Werribee",
                    "303": "West Footscray",
                    "304": "West Melbourne",
                    "305": "Westmeadows",
                    "306": "Wheelers Hill",
                    "307": "Whittlesea",
                    "308": "Williams Landing",
                    "309": "Williamstown",
                    "310": "Williamstown North",
                    "311": "Windsor",
                    "312": "Wollert",
                    "313": "Wyndham Vale",
                    "314": "Yallambie",
                    "315": "Yarra Glen",
                    "316": "Yarraville",
                }
            }
        },
        {
            "Label": "Room Number",
            "Data": {
                "Description": "Please choose room number",
                "Form": {
                    "1": "1",
                    "2": "2",
                    "3": "3",
                    "4": "4",
                    "5": "5",
                    "6": "6",
                    "7": "7",
                    "8": "8",
                    "9": "9",
                    "10": "10",
                    "11": "11",
                    "12": "12",
                }
            }
        },
        {
            "Label": "House Type",
            "Data": {
                "Description": "Please choose house type",
                "Form": {
                    "unit": "u",
                    "house": "h",
                    "townhouse": "t",
                }
            }
        },
        {
            "Label": "Number of bathroom",
            "Data": {
                "Description": "Please choose number of bathroom",
                "Form": {
                    "1": "1",
                    "2": "2",
                    "3": "3",
                    "4": "4",
                    "5": "5",
                    "6": "6",
                    "7": "7",
                    "8": "8",
                    "9": "9",
                }
            }
        },
        {
            "Label": "CouncilArea",
            "Data":{
                "Description": "Please select a council",
                "Form": {
                    "1": "Glen Eira City Council",
                    "2": "Darebin City Council",
                    "3": "Maribyrnong City Council",
                    "4": "Brimbank City Council",
                    "5": "Moreland City Council",
                    "6": "Boroondara City Council",
                    "7": "Melton City Council",
                    "8": "Moonee Valley City Council",
                    "9": "Hobsons Bay City Council",
                    "10": "Greater Dandenong City Council",
                    "11": "Kingston City Council",
                    "12": "Hume City Council",
                    "13": "Wyndham City Council",
                    "14": "Yarra City Council",
                    "15": "Whittlesea City Council",
                    "16": "Port Phillip City Council",
                    "17": "Melbourne City Council",
                    "18": "Banyule City Council",
                    "19": "Mitchell Shire Council",
                    "20": "Bayside City Council",
                    "21": "Frankston City Council",
                    "22": "Monash City Council",
                    "23": "Casey City Council",
                    "24": "Stonnington City Council",
                    "25": "Moorabool Shire Council",
                    "26": "Macedon Ranges Shire Council",
                    "27": "Cardinia Shire Council",
                    "28": "Manningham City Council",
                    "29": "Nillumbik Shire Council",
                    "30": "Knox City Council",
                    "31": "Yarra Ranges Shire Council",
                    "32": "Maroondah City Council",
                    "33": "Whitehorse City Council",
                }

            }
        },
        {
            "Label": "Regionname",
            "Data": {
                "Description": "Please select a region",
                "Form": {
                    "1": "Southern Metropolitan",
                    "2": "Northern Metropolitan",
                    "3": "Western Metropolitan",
                    "4": "Western Victoria",
                    "5": "South-Eastern Metropolitan",
                    "6": "Northern Victoria",
                    "7": "Eastern Metropolitan",
                    "8": "Eastern Victoria",
                }
            }
        }
    ]
}